import { en_US, km_KH, zh_CN } from "ng-zorro-antd/i18n";

export const APP_STORAGE_KEY = {
  Authorized: "authorized",
  RefreshToken: "RefreshToken",
  Language: "vip-lang",
  Tenant: "vip-tenant",
  App: "vip-appinfo",
};

export const BRANCH_STORAGE_KEY = "branchStorageKey";
export const SIDE_EXPAND_COLLAPSED = "sideExpandCollapsed";

export enum REPORT_RENDER_TYPES {
  HTML5 = 1,
  Excel = 2,
  Word = 3,
  Pdf = 4,
}

export enum PageSize {
  A1 = 1,
  A2 = 2,
  A3 = 3,
  A4 = 4,
  A5 = 5,
}
export enum Orientation {
  Portrait = 1,
  Landscape = 2,
}

export enum ReportParamDisplay {
  Inline = 1,
  Modal = 2,
}

export enum ItemAvailability {
  Yes = 1,
  No = 2,
  Hidden = 3,
}

export enum PenaltyType {
  FixedAmount = 1,
  Percentage = 2,
}

export enum DeadlineType {
  Day = 1,
  Hour = 2,
}

export enum RateType {
  Default = 1,
  Seasonal = 2,
}

export const PAGE_SIZE_OPTION = [10, 25, 50, 100];

export const ADDRESS_FILTER_OPTION = {
  Province: "province",
  District: "district",
  Commune: "commune",
  Village: "village",
};

export const REPORT_NAME = {
  Complain: "ListOfComplaint",
  Individual: "Individual",
  AuditAndTracking: "AuditAndTracking",
  Management: "Management",
  ManagementChart: "ManagementChart",
  Operational: "Operational",
  UserRetrievingData: "UserRetrievingData",
};

export const Locale: { KH: any; EN: any; ZH: any; DEFAULT: any } | any = {
  KH: { local: km_KH, localId: "km" },
  EN: { local: en_US, localId: "en" },
  ZH: { local: zh_CN, localId: "zh" },
  DEFAULT: { local: km_KH, localId: "km" },
};

export const LANGUAGES: {
  key: { local: any; localId: string };
  image: string;
  label: string;
}[] = [
  { key: Locale.KH, label: "ភាសាខ្មែរ", image: "./assets/image/kh_FLAG.png" },
  { key: Locale.EN, label: "English", image: "./assets/image/en_FLAG.png" },
  { key: Locale.ZH, label: "中文", image: "./assets/image/ch_FLAG.png" },
];

export const SIZE_COLUMNS = {
  DRAG: "20px",
  ID: "45px",
  NAME: "200px",
  CODE: "100px",
  DESCRIPTION: "150px",
  ACTION: "180px",
  STATUS: "140px",
  DATE: "180px",
  DATE_RANGE: "220px",
  TOTAL: "150px",
  DROP: "8px",
  ICON: "30px",
  NOTE: "350px",
  PHONE: "200px",
  IMAGE: "80px",
  Amenity: "400px",
  GENDER: "100px",
  NORMAL: "12%",
  FORMAT: "150px",
  COLOR: "120px",
  SMALL: "50px",
  MEDIUM: "150px",
  LARGE: "300px",
};

export const AuthKeys = {
 APP : 38000,
 APP__AGENT : 38002,
 APP__AGENT__ADD : 38013,
 APP__AGENT__EDIT : 38014,
 APP__AGENT__LIST : 38012,
 APP__AGENT__REMOVE : 38016,
 APP__AGENT__VIEW : 38015,
 APP__HOME : 38051,
 APP__MEMBER : 38001,
 APP__MEMBER__ADD : 38008,
 APP__MEMBER__EDIT : 38009,
 APP__MEMBER__LIST : 38007,
 APP__MEMBER__REMOVE : 38011,
 APP__MEMBER__VIEW : 38010,
 APP__MEMBER__VIEW__ACCOUNT : 38037,
 APP__MEMBER__VIEW__ACCOUNT__LIST : 38106,
 APP__MEMBER__VIEW__ACCOUNT__POINT : 38044,
 APP__MEMBER__VIEW__ACCOUNT__POINT__ADJUST : 38049,
 APP__MEMBER__VIEW__ACCOUNT__POINT__EARN : 38050,
 APP__MEMBER__VIEW__ACCOUNT__POINT__VIEW : 38107,
 APP__MEMBER__VIEW__ACCOUNT__WALLET : 38043,
 APP__MEMBER__VIEW__ACCOUNT__WALLET__ADJUST : 38048,
 APP__MEMBER__VIEW__ACCOUNT__WALLET__TOPUP : 38047,
 APP__MEMBER__VIEW__ACCOUNT__WALLET__VIEW : 38108,
 APP__MEMBER__VIEW__CARD : 38036,
 APP__MEMBER__VIEW__CARD__ADD : 38039,
 APP__MEMBER__VIEW__CARD__EDIT : 38040,
 APP__MEMBER__VIEW__CARD__LIST : 38038,
 APP__MEMBER__VIEW__CARD__REMOVE : 38042,
 APP__MEMBER__VIEW__CARD__VIEW : 38041,
 APP__OFFER : 38003,
 APP__OFFER__ADD : 38018,
 APP__OFFER__EDIT : 38019,
 APP__OFFER__LIST : 38017,
 APP__OFFER__REMOVE : 38021,
 APP__OFFER__VIEW : 38020,
 APP__REDEMPTION : 38004,
 APP__REDEMPTION__ADD : 38023,
 APP__REDEMPTION__LIST : 38022,
 APP__REDEMPTION__PRINT : 38109,
 APP__REDEMPTION__REMOVE : 38026,
 APP__REDEMPTION__VIEW : 38025,
 APP__REPORT : 38035,
 APP__REPORT__PRINT : 38093,
 APP__REPORT__PRINT__REDEEMPRINT : 38094,
 APP__REPORT__REDEEM : 38091,
 APP__REPORT__REDEEM__REDEEMDETAIL : 38097,
 APP__REPORT__REDEEM__REDEEMSUMMARY : 38096,
 APP__REPORT__TRANSACTION : 38092,
 APP__REPORT__TRANSACTION__TRANSACTIONDETAILREPORT : 38095,
 APP__REPORT__TRANSACTION_MOBILE : 38090,
 APP__REPORT__TRANSACTION_MOBILE__TRANSACTIONDETAIL : 38099,
 APP__REPORT__TRANSACTION_MOBILE__TRANSACTIONSUMMARY : 38098,
 APP__SETTING : 38005,
 APP__SETTING__AUTO_NUMBER : 38034,
 APP__SETTING__AUTO_NUMBER__ADD : 38073,
 APP__SETTING__AUTO_NUMBER__EDIT : 38074,
 APP__SETTING__AUTO_NUMBER__LIST : 38072,
 APP__SETTING__AUTO_NUMBER__REMOVE : 38076,
 APP__SETTING__AUTO_NUMBER__VIEW : 38075,
 APP__SETTING__BRANCH : 38028,
 APP__SETTING__BRANCH__ADD : 38083,
 APP__SETTING__BRANCH__EDIT : 38084,
 APP__SETTING__BRANCH__LIST : 38082,
 APP__SETTING__BRANCH__REMOVE : 38086,
 APP__SETTING__BRANCH__VIEW : 38085,
 APP__SETTING__CURRENCY : 38031,
 APP__SETTING__CURRENCY__ADD : 38058,
 APP__SETTING__CURRENCY__EDIT : 38059,
 APP__SETTING__CURRENCY__LIST : 38057,
 APP__SETTING__CURRENCY__REMOVE : 38061,
 APP__SETTING__CURRENCY__VIEW : 38060,
 APP__SETTING__LOCATION : 38032,
 APP__SETTING__LOCATION__ADD : 38078,
 APP__SETTING__LOCATION__EDIT : 38079,
 APP__SETTING__LOCATION__LIST : 38077,
 APP__SETTING__LOCATION__REMOVE : 38081,
 APP__SETTING__LOCATION__VIEW : 38080,
 APP__SETTING__LOOKUP : 38027,
 APP__SETTING__LOOKUP__ADD : 38053,
 APP__SETTING__LOOKUP__EDIT : 38054,
 APP__SETTING__LOOKUP__LIST : 38052,
 APP__SETTING__LOOKUP__REMOVE : 38056,
 APP__SETTING__LOOKUP__VIEW : 38055,
 APP__SETTING__MEMBER_CLASS : 38029,
 APP__SETTING__MEMBER_CLASS__ADD : 38068,
 APP__SETTING__MEMBER_CLASS__EDIT : 38069,
 APP__SETTING__MEMBER_CLASS__LIST : 38067,
 APP__SETTING__MEMBER_CLASS__REMOVE : 38071,
 APP__SETTING__MEMBER_CLASS__VIEW : 38070,
 APP__SETTING__OFFER_GROUP : 38030,
 APP__SETTING__OFFER_GROUP__ADD : 38063,
 APP__SETTING__OFFER_GROUP__EDIT : 38064,
 APP__SETTING__OFFER_GROUP__LIST : 38062,
 APP__SETTING__OFFER_GROUP__REMOVE : 38066,
 APP__SETTING__OFFER_GROUP__VIEW : 38065,
 APP__SETTING__REPORT : 38006,
 APP__SETTING__REPORT__ADD : 38101,
 APP__SETTING__REPORT__EDIT : 38102,
 APP__SETTING__REPORT__LIST : 38100,
 APP__SETTING__REPORT__REMOVE : 38104,
 APP__SETTING__REPORT__VIEW : 38103,
 APP__SETTING__SYSTEM_SETTING : 38033,
 APP__SETTING__SYSTEM_SETTING__AUTO_NUMBER : 38088,
 APP__SETTING__SYSTEM_SETTING__COMPANY_SETTING : 38087,
}